// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: "AIzaSyAmfZK6EMulqiNNrBXJeOwqfvod0ol_oGg",
    authDomain: "my-crm-f9e54.firebaseapp.com",
    projectId: "my-crm-f9e54",
    storageBucket: "my-crm-f9e54.firebasestorage.app",
    messagingSenderId: "376939281803",
    appId: "1:376939281803:web:eceb142ae0b0dcedf3c38e",
    measurementId: "G-RXX60RPDNT",
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA-dyFsSkTgCQG88F2GF5GUQbIYOvqOXw4',
    appId: '1:376939281803:android:abcdef123456',
    messagingSenderId: '376939281803',
    projectId: 'my-crm-f9e54',
    storageBucket: 'my-crm-f9e54.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBjt4YpYKKK_gn4hf_ozdgB64Jdf-9_g48',
    appId: '1:376939281803:ios:21a49b747c58fb33f3c38e',
    messagingSenderId: '376939281803',
    projectId: 'my-crm-f9e54',
    storageBucket: 'my-crm-f9e54.firebasestorage.com',
    iosClientId: '123456789-abcdefghijklmnop.apps.googleusercontent.com',
    iosBundleId: 'com.rouelleconsulting.crm',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDemo-macOS-Key-Replace-With-Real-Key',
    appId: '1:123456789:ios:abcdef123456',
    messagingSenderId: '123456789',
    projectId: 'your-project-id',
    storageBucket: 'your-project-id.appspot.com',
    iosClientId: '123456789-abcdefghijklmnop.apps.googleusercontent.com',
    iosBundleId: 'com.example.nrCrmFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: "AIzaSyAmfZK6EMulqiNNrBXJeOwqfvod0ol_oGg",
    authDomain: "my-crm-f9e54.firebaseapp.com",
    projectId: "my-crm-f9e54",
    storageBucket: "my-crm-f9e54.firebasestorage.app",
    messagingSenderId: "376939281803",
    appId: "1:376939281803:web:eceb142ae0b0dcedf3c38e",
    measurementId: "G-RXX60RPDNT",
  );
}
